# Generated by Django 5.1.6 on 2025-03-05 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_update', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('estimated_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('work', models.CharField(max_length=100)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('work_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_update.taskstate')),
            ],
        ),
    ]
